name: app_senturer_banco
description: "Aplicación móvil del banco digital SENTURER"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_senturer.png
    - assets/icons/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#1E3A5F"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  icons_path: "assets/icons"
